package domain

import "errors"

// GL errors (from repository.go + models.go)
var (
	ErrAccountNotFound       = errors.New("account not found")
	ErrAccountCodeExists     = errors.New("account code already exists")
	ErrAccountHasChildren    = errors.New("account has children, cannot delete")
	ErrAccountHasBalance     = errors.New("account has balance, cannot delete")
	ErrJournalNotFound       = errors.New("journal entry not found")
	ErrJournalAlreadyPosted  = errors.New("journal entry already posted")
	ErrJournalAlreadyCancelled = errors.New("journal entry already cancelled")
	ErrJournalPeriodClosed   = errors.New("period is closed, cannot post")
	ErrPeriodNotFound        = errors.New("period not found")
	ErrPeriodAlreadyClosed   = errors.New("period already closed")
	ErrAccountInactive       = errors.New("account is inactive")
	ErrJournalAlreadyDraft   = errors.New("journal entry is draft, not posted")
	ErrUserNotFound          = errors.New("user not found")
	ErrUsernameExists        = errors.New("username already exists")
	ErrUserInactive          = errors.New("user is inactive")
	ErrRateNotFound          = errors.New("exchange rate not found")
	ErrTemplateNotFound      = errors.New("closing template not found")
	ErrPeriodHasEntries      = errors.New("period has posted entries, cannot reopen")
	ErrJournalAlreadyReviewed = errors.New("journal entry already reviewed")
	ErrJournalAlreadyApproved = errors.New("journal entry already approved")

	ErrAccountCodeRequired          = errors.New("account code is required")
	ErrAccountNameRequired          = errors.New("account name is required")
	ErrAccountInvalidType           = errors.New("account type is invalid")
	ErrAccountCodeInvalid           = errors.New("account code must be digits, min 3 chars")
	ErrAccountCodeInvalidHierarchy  = errors.New("account code must start with parent code prefix")
	ErrAccountStatusInvalid         = errors.New("account status is invalid")
	ErrAccountAlreadyFrozen         = errors.New("account is already frozen")
	ErrAccountNotFrozen             = errors.New("account is not frozen")
	ErrAccountFrozen                = errors.New("account is frozen, cannot post")
	ErrApprovalNotFound             = errors.New("approval request not found")
	ErrApprovalAlreadyProcessed     = errors.New("approval request already processed")
	ErrSelfApproval                 = errors.New("cannot self-approve")
	ErrApprovalExpired              = errors.New("approval request has expired")
	ErrVersionNotFound              = errors.New("version not found")
	ErrMappingNotFound              = errors.New("account mapping not found")
	ErrMappingExists                = errors.New("account mapping already exists")
	ErrAnalysisNotFound             = errors.New("account analysis not found")
	ErrIFRSMappingNotFound          = errors.New("IFRS mapping not found")
	ErrIFRSMappingExists            = errors.New("IFRS mapping already exists")
	ErrFreezeReasonRequired         = errors.New("freeze reason is required")
	ErrApprovalReasonRequired       = errors.New("approval reason is required")
	ErrReviewNoteRequired           = errors.New("review note is required")
	ErrJournalEntryNoLines          = errors.New("journal entry must have at least one line")
	ErrJournalEntryUnbalanced       = errors.New("total debit must equal total credit")
	ErrJournalEntryInvalidDate      = errors.New("entry date is required")
	ErrJournalEntryNoDescription    = errors.New("description is required")
	ErrJournalLineInvalidAmount     = errors.New("line amount must be positive")
	ErrInvalidCurrencyCode          = errors.New("currency code must be 3 chars")
	ErrInvalidExchangeRate          = errors.New("exchange rate must be positive")
	ErrInvalidUserRole              = errors.New("invalid user role")
	ErrUsernameRequired             = errors.New("username is required")
	ErrPasswordRequired             = errors.New("password is required")
	ErrPasswordTooShort             = errors.New("password must be at least 12 characters")
	ErrPasswordNoUpper              = errors.New("password must contain an uppercase letter")
	ErrPasswordNoLower              = errors.New("password must contain a lowercase letter")
	ErrPasswordNoDigit              = errors.New("password must contain a digit")
	ErrPasswordNoSpecial            = errors.New("password must contain a special character")
	ErrPasswordReuse                = errors.New("password has been used recently")
	ErrPasswordExpired              = errors.New("password has expired, please change it")
	ErrInvalidCurrentPassword       = errors.New("current password is incorrect")
	ErrInvalidCredentials           = errors.New("invalid credentials")
	ErrAccountLocked                = errors.New("account is locked due to too many attempts")
	ErrRefreshTokenExpired          = errors.New("refresh token has expired")
	ErrRefreshTokenRevoked          = errors.New("refresh token has been revoked")
	ErrInvalidRefreshToken          = errors.New("invalid refresh token")
	ErrPasswordResetTokenExpired    = errors.New("password reset token has expired")
	ErrInvalidPasswordResetToken    = errors.New("invalid password reset token")
	Err2FARequired                  = errors.New("two-factor authentication is required")
	ErrInvalid2FACode               = errors.New("invalid two-factor authentication code")
	Err2FANotSetup                  = errors.New("two-factor authentication is not set up")
	Err2FAAlreadyEnabled            = errors.New("two-factor authentication is already enabled")
	ErrRateLimited                  = errors.New("too many requests, please try again later")
	ErrSessionExpired               = errors.New("session has expired")
)

// Period validation errors (used in models.go Validate methods)
var (
	ErrPeriodYearOutOfRange = errors.New("year out of range (2000-2100)")
	ErrPeriodMonthInvalid   = errors.New("month must be 1-12")
	ErrPeriodDateRequired   = errors.New("start_date and end_date are required")
	ErrPeriodEndBeforeStart = errors.New("end_date must be after start_date")
	ErrPeriodStatusInvalid  = errors.New("invalid period status")
)

// COA validation errors
var (
	ErrEntityTypeRequired   = errors.New("entity type is required")
	ErrEntityIDRequired     = errors.New("entity id is required")
	ErrRequestTypeRequired  = errors.New("request type is required")
	ErrRequesterRequired    = errors.New("requester is required")
	ErrSourceRegimeRequired = errors.New("source regime is required")
	ErrTargetRegimeRequired = errors.New("target regime is required")
	ErrOldCodeRequired      = errors.New("old code is required")
	ErrNewCodeRequired      = errors.New("new code is required")
	ErrMappingTypeInvalid   = errors.New("mapping type must be DIRECT, MERGE, SPLIT, or CUSTOM")
	ErrSplitRatioRequired   = errors.New("split ratio must be positive for SPLIT mappings")
	ErrVASCodeRequired      = errors.New("VAS code is required")
	ErrIFRSCodeRequired     = errors.New("IFRS code is required")
)

// Company errors
var (
	ErrCompanyNotFound             = errors.New("company not found")
	ErrCompanyTaxCodeExists        = errors.New("tax code already registered")
	ErrCompanyInactive             = errors.New("company is inactive")
	ErrCompanyCodeRequired         = errors.New("tax code is required")
	ErrCompanyNameRequired         = errors.New("company name is required")
	ErrCompanyInvalidRegime        = errors.New("invalid accounting regime")
	ErrCompanyInvalidLegalForm     = errors.New("invalid legal form")
	ErrInvalidTaxCodeFormat        = errors.New("tax code must be 10 or 13 digits")
	ErrBranchNotFound              = errors.New("branch not found")
	ErrBranchTaxCodeExists         = errors.New("branch tax code already exists")
	ErrFiscalYearNotFound          = errors.New("fiscal year not found")
	ErrFiscalYearExists            = errors.New("fiscal year already exists")
	ErrPeriodV2NotFound            = errors.New("period not found")
	ErrPeriodPermanentlyClosed     = errors.New("period permanently closed cannot be reopened")
	ErrDepartmentNotFound          = errors.New("department not found")
	ErrDepartmentCodeExists        = errors.New("department code already exists")
	ErrEmployeeNotFound            = errors.New("employee not found")
	ErrEmployeeCodeExists          = errors.New("employee code already exists")
	ErrBankAccountNotFound         = errors.New("bank account not found")
	ErrBankAccountCodeExists       = errors.New("bank account number already exists")
	ErrEInvoiceNotFound            = errors.New("e-invoice pattern not found")
	ErrEInvoicePatternExists       = errors.New("e-invoice pattern already exists")
	ErrSignatureNotFound           = errors.New("digital signature not found")
	ErrSignatureExists             = errors.New("digital signature already exists")
	ErrIntegrationNotFound         = errors.New("integration profile not found")
	ErrIntegrationExists           = errors.New("integration profile already exists")
	ErrFiscalYearChangeWithEntries = errors.New("fiscal year has journal entries")
	ErrAccessDenied                = errors.New("access denied to company")
	ErrCompanySwitchSame           = errors.New("already in this company context")
	ErrInvalidTaxCode              = errors.New("invalid tax code format")
)

// Cash module errors
var (
	ErrCashReceiptNotFound    = errors.New("cash receipt not found")
	ErrCashPaymentNotFound    = errors.New("cash payment not found")
	ErrCashTransferNotFound   = errors.New("cash transfer not found")
	ErrCashBookNotFound       = errors.New("cash book not found")
	ErrPettyCashFundNotFound  = errors.New("petty cash fund not found")
	ErrCashInventoryNotFound  = errors.New("cash inventory not found")
	ErrVoucherNoExists        = errors.New("voucher number already exists")
	ErrCashNotApproved        = errors.New("voucher not approved")
	ErrCashAlreadyPosted      = errors.New("voucher already posted")
	ErrCashAlreadyApproved    = errors.New("voucher already approved")
	ErrCashAlreadyRejected    = errors.New("voucher already rejected")
	ErrCashInvalidStatus      = errors.New("invalid voucher status transition")
	ErrCashAmountRequired     = errors.New("cash amount must be positive")
	ErrCashAccountInvalid     = errors.New("cash account required")
	ErrCashImbalance          = errors.New("debit and credit must balance")
	ErrCashInsufficientBalance = errors.New("insufficient cash balance")
	ErrFundAlreadyClosed      = errors.New("petty cash fund already closed")
	ErrFundNotActive          = errors.New("petty cash fund not active")
	ErrInventoryCompleted     = errors.New("cash inventory already completed")
	ErrCurrencyMismatch       = errors.New("currency mismatch")
	ErrExchangeRateRequired   = errors.New("exchange rate required for foreign currency")
	ErrApprovalRequired       = errors.New("voucher must be approved before posting")
	ErrSelfCashApproval       = errors.New("cannot self-approve cash voucher")
)

// Advance errors
var (
	ErrAdvanceNotFound       = errors.New("advance request not found")
	ErrAdvanceAlreadyPaid    = errors.New("advance already paid")
	ErrAdvanceAlreadySettled = errors.New("advance already settled")
	ErrSettlementNotFound    = errors.New("advance settlement not found")
	ErrSettlementAlreadyPaid = errors.New("settlement already paid")
)

// Tax module errors
var (
	ErrDeclarationNotFound       = errors.New("tax declaration not found")
	ErrDeclarationTypeInvalid    = errors.New("invalid declaration type")
	ErrDeclarationStatusInvalid  = errors.New("invalid declaration status")
	ErrDeclarationAlreadySubmitted = errors.New("declaration already submitted")
	ErrDeclarationNotEditable    = errors.New("declaration is not editable")
	ErrCompanyIDRequired         = errors.New("company id is required")
	ErrPeriodNumberInvalid       = errors.New("invalid period number")
	ErrTaxRateNotFound           = errors.New("tax rate not found")
	ErrTaxRateCodeExists         = errors.New("tax rate code already exists")
	ErrTaxPaymentNotFound        = errors.New("tax payment not found")
	ErrPaymentAmountRequired     = errors.New("payment amount is required")
	ErrPaymentDueDateRequired    = errors.New("payment due date is required")
	ErrInvoiceNotFound           = errors.New("e-invoice not found")
	ErrInvoicePatternRequired    = errors.New("invoice pattern is required")
	ErrInvoiceNoLines            = errors.New("invoice must have at least one line")
	ErrInvoiceVATMismatch        = errors.New("VAT amount does not match line total * VAT rate")
	ErrInvoiceSubtotalMismatch   = errors.New("subtotal does not match sum of line totals")
	ErrInvoiceVATTotalMismatch   = errors.New("VAT amount does not match sum of line VAT")
	ErrInvoiceGrandTotalMismatch = errors.New("grand total must equal subtotal + VAT")
	ErrInvoiceStatusInvalid      = errors.New("invalid invoice status")
	ErrOriginalInvoiceRequired   = errors.New("original invoice ID required for adjustment/replacement/cancellation")
	ErrBuyerNameRequired         = errors.New("buyer name is required")
	ErrCalendarNotFound          = errors.New("tax calendar entry not found")
	ErrTaxAlertNotFound          = errors.New("tax alert not found")
	ErrAuditCaseNotFound         = errors.New("audit case not found")
	ErrValidationFailed          = errors.New("tax validation failed")
	ErrCalculationFailed         = errors.New("tax calculation failed")
	ErrXMLGenerationFailed       = errors.New("XML generation failed")

	// Opening balance errors
	ErrOpeningBalanceNotFound     = errors.New("opening balance not found")
	ErrOpeningBalanceExists       = errors.New("opening balance already exists for this account and period")
	ErrOpeningBalanceNotBalanced  = errors.New("total debit must equal total credit")
	ErrParentAccountBalance       = errors.New("parent account cannot have opening balance")
	ErrAmountRequired             = errors.New("debit or credit amount is required")
	ErrBothDebitAndCredit         = errors.New("cannot have both debit and credit, use one")
	ErrDuplicateOpeningBalance    = errors.New("duplicate opening balance for account in this period")
	ErrPeriodNotOpen              = errors.New("period is not open")
	ErrOpeningBalanceApproved     = errors.New("opening balance already approved, use correction")
	ErrOpeningBalanceRejected     = errors.New("opening balance was rejected")
	ErrOpeningBalanceImmutable    = errors.New("opening balance is immutable after approval")
	ErrSelfApprovalOB             = errors.New("cannot self-approve opening balance")
	ErrCorrectionReasonRequired   = errors.New("correction reason is required")
	ErrCarryForwardExists         = errors.New("carry-forward already exists for this period pair")
	ErrCarryForwardNotAllowed     = errors.New("cannot carry forward, target period has entries")
	ErrCircular99MappingNotFound  = errors.New("circular 99 mapping not found")
	ErrCircular99MappingExists    = errors.New("circular 99 mapping already exists")
	ErrMigrationIncomplete        = errors.New("migration is incomplete, some accounts not mapped")
	ErrEntityNotInCompany         = errors.New("entity does not belong to this company")
	ErrDetailSumMismatch          = errors.New("detail line sum must equal opening balance total")
	ErrOpeningBalanceAlreadySubmitted = errors.New("opening balance already submitted for approval")
	ErrPeriodNotClosed            = errors.New("source period must be closed for carry-forward")
)
