package domain

import "errors"

// GL errors (from repository.go + models.go)
var (
	ErrAccountNotFound       = errors.New("account not found")
	ErrAccountCodeExists     = errors.New("account code already exists")
	ErrAccountHasChildren    = errors.New("account has children, cannot delete")
	ErrAccountHasBalance     = errors.New("account has balance, cannot delete")
	ErrJournalNotFound       = errors.New("journal entry not found")
	ErrJournalAlreadyPosted  = errors.New("journal entry already posted")
	ErrJournalAlreadyCancelled = errors.New("journal entry already cancelled")
	ErrJournalPeriodClosed   = errors.New("period is closed, cannot post")
	ErrPeriodNotFound        = errors.New("period not found")
	ErrPeriodAlreadyClosed   = errors.New("period already closed")
	ErrAccountInactive       = errors.New("account is inactive")
	ErrJournalAlreadyDraft   = errors.New("journal entry is draft, not posted")
	ErrUserNotFound          = errors.New("user not found")
	ErrUsernameExists        = errors.New("username already exists")
	ErrUserInactive          = errors.New("user is inactive")
	ErrRateNotFound          = errors.New("exchange rate not found")
	ErrTemplateNotFound      = errors.New("closing template not found")
	ErrPeriodHasEntries      = errors.New("period has posted entries, cannot reopen")
	ErrJournalAlreadyReviewed = errors.New("journal entry already reviewed")
	ErrJournalAlreadyApproved = errors.New("journal entry already approved")

	ErrAccountCodeRequired          = errors.New("account code is required")
	ErrAccountNameRequired          = errors.New("account name is required")
	ErrAccountInvalidType           = errors.New("account type is invalid")
	ErrAccountCodeInvalid           = errors.New("account code must be digits, min 3 chars")
	ErrAccountCodeInvalidHierarchy  = errors.New("account code must start with parent code prefix")
	ErrAccountStatusInvalid         = errors.New("account status is invalid")
	ErrAccountAlreadyFrozen         = errors.New("account is already frozen")
	ErrAccountNotFrozen             = errors.New("account is not frozen")
	ErrAccountFrozen                = errors.New("account is frozen, cannot post")
	ErrApprovalNotFound             = errors.New("approval request not found")
	ErrApprovalAlreadyProcessed     = errors.New("approval request already processed")
	ErrSelfApproval                 = errors.New("cannot self-approve")
	ErrApprovalExpired              = errors.New("approval request has expired")
	ErrVersionNotFound              = errors.New("version not found")
	ErrMappingNotFound              = errors.New("account mapping not found")
	ErrMappingExists                = errors.New("account mapping already exists")
	ErrAnalysisNotFound             = errors.New("account analysis not found")
	ErrIFRSMappingNotFound          = errors.New("IFRS mapping not found")
	ErrIFRSMappingExists            = errors.New("IFRS mapping already exists")
	ErrFreezeReasonRequired         = errors.New("freeze reason is required")
	ErrApprovalReasonRequired       = errors.New("approval reason is required")
	ErrReviewNoteRequired           = errors.New("review note is required")
	ErrJournalEntryNoLines          = errors.New("journal entry must have at least one line")
	ErrJournalEntryUnbalanced       = errors.New("total debit must equal total credit")
	ErrJournalEntryInvalidDate      = errors.New("entry date is required")
	ErrJournalEntryNoDescription    = errors.New("description is required")
	ErrJournalLineInvalidAmount     = errors.New("line amount must be positive")
	ErrInvalidCurrencyCode          = errors.New("currency code must be 3 chars")
	ErrInvalidExchangeRate          = errors.New("exchange rate must be positive")
	ErrInvalidUserRole              = errors.New("invalid user role")
	ErrUsernameRequired             = errors.New("username is required")
	ErrPasswordRequired             = errors.New("password is required")
	ErrPasswordTooShort             = errors.New("password must be at least 12 characters")
	ErrPasswordNoUpper              = errors.New("password must contain an uppercase letter")
	ErrPasswordNoLower              = errors.New("password must contain a lowercase letter")
	ErrPasswordNoDigit              = errors.New("password must contain a digit")
	ErrPasswordNoSpecial            = errors.New("password must contain a special character")
	ErrPasswordReuse                = errors.New("password has been used recently")
	ErrPasswordExpired              = errors.New("password has expired, please change it")
	ErrInvalidCurrentPassword       = errors.New("current password is incorrect")
	ErrInvalidCredentials           = errors.New("invalid credentials")
	ErrAccountLocked                = errors.New("account is locked due to too many attempts")
	ErrRefreshTokenExpired          = errors.New("refresh token has expired")
	ErrRefreshTokenRevoked          = errors.New("refresh token has been revoked")
	ErrInvalidRefreshToken          = errors.New("invalid refresh token")
	ErrPasswordResetTokenExpired    = errors.New("password reset token has expired")
	ErrInvalidPasswordResetToken    = errors.New("invalid password reset token")
	Err2FARequired                  = errors.New("two-factor authentication is required")
	ErrInvalid2FACode               = errors.New("invalid two-factor authentication code")
	Err2FANotSetup                  = errors.New("two-factor authentication is not set up")
	Err2FAAlreadyEnabled            = errors.New("two-factor authentication is already enabled")
	ErrRateLimited                  = errors.New("too many requests, please try again later")
	ErrSessionExpired               = errors.New("session has expired")
)

// Period validation errors (used in models.go Validate methods)
var (
	ErrPeriodYearOutOfRange = errors.New("year out of range (2000-2100)")
	ErrPeriodMonthInvalid   = errors.New("month must be 1-12")
	ErrPeriodDateRequired   = errors.New("start_date and end_date are required")
	ErrPeriodEndBeforeStart = errors.New("end_date must be after start_date")
	ErrPeriodStatusInvalid  = errors.New("invalid period status")
)

// COA validation errors
var (
	ErrEntityTypeRequired   = errors.New("entity type is required")
	ErrEntityIDRequired     = errors.New("entity id is required")
	ErrRequestTypeRequired  = errors.New("request type is required")
	ErrRequesterRequired    = errors.New("requester is required")
	ErrSourceRegimeRequired = errors.New("source regime is required")
	ErrTargetRegimeRequired = errors.New("target regime is required")
	ErrOldCodeRequired      = errors.New("old code is required")
	ErrNewCodeRequired      = errors.New("new code is required")
	ErrMappingTypeInvalid   = errors.New("mapping type must be DIRECT, MERGE, SPLIT, or CUSTOM")
	ErrSplitRatioRequired   = errors.New("split ratio must be positive for SPLIT mappings")
	ErrVASCodeRequired      = errors.New("VAS code is required")
	ErrIFRSCodeRequired     = errors.New("IFRS code is required")
)

// Company errors
var (
	ErrCompanyNotFound             = errors.New("company not found")
	ErrCompanyTaxCodeExists        = errors.New("tax code already registered")
	ErrCompanyInactive             = errors.New("company is inactive")
	ErrCompanyCodeRequired         = errors.New("tax code is required")
	ErrCompanyNameRequired         = errors.New("company name is required")
	ErrCompanyInvalidRegime        = errors.New("invalid accounting regime")
	ErrCompanyInvalidLegalForm     = errors.New("invalid legal form")
	ErrInvalidTaxCodeFormat        = errors.New("tax code must be 10 or 13 digits")
	ErrBranchNotFound              = errors.New("branch not found")
	ErrBranchTaxCodeExists         = errors.New("branch tax code already exists")
	ErrFiscalYearNotFound          = errors.New("fiscal year not found")
	ErrFiscalYearExists            = errors.New("fiscal year already exists")
	ErrPeriodV2NotFound            = errors.New("period not found")
	ErrPeriodPermanentlyClosed     = errors.New("period permanently closed cannot be reopened")
	ErrDepartmentNotFound          = errors.New("department not found")
	ErrDepartmentCodeExists        = errors.New("department code already exists")
	ErrEmployeeNotFound            = errors.New("employee not found")
	ErrEmployeeCodeExists          = errors.New("employee code already exists")
	ErrBankAccountNotFound         = errors.New("bank account not found")
	ErrBankAccountCodeExists       = errors.New("bank account number already exists")
	ErrEInvoiceNotFound            = errors.New("e-invoice pattern not found")
	ErrEInvoicePatternExists       = errors.New("e-invoice pattern already exists")
	ErrSignatureNotFound           = errors.New("digital signature not found")
	ErrSignatureExists             = errors.New("digital signature already exists")
	ErrIntegrationNotFound         = errors.New("integration profile not found")
	ErrIntegrationExists           = errors.New("integration profile already exists")
	ErrFiscalYearChangeWithEntries = errors.New("fiscal year has journal entries")
	ErrAccessDenied                = errors.New("access denied to company")
	ErrCompanySwitchSame           = errors.New("already in this company context")
	ErrInvalidTaxCode              = errors.New("invalid tax code format")
)

// Cash module errors
var (
	ErrCashReceiptNotFound    = errors.New("cash receipt not found")
	ErrCashPaymentNotFound    = errors.New("cash payment not found")
	ErrCashTransferNotFound   = errors.New("cash transfer not found")
	ErrCashBookNotFound       = errors.New("cash book not found")
	ErrPettyCashFundNotFound  = errors.New("petty cash fund not found")
	ErrCashInventoryNotFound  = errors.New("cash inventory not found")
	ErrVoucherNoExists        = errors.New("voucher number already exists")
	ErrCashNotApproved        = errors.New("voucher not approved")
	ErrCashAlreadyPosted      = errors.New("voucher already posted")
	ErrCashAlreadyApproved    = errors.New("voucher already approved")
	ErrCashAlreadyRejected    = errors.New("voucher already rejected")
	ErrCashInvalidStatus      = errors.New("invalid voucher status transition")
	ErrCashAmountRequired     = errors.New("cash amount must be positive")
	ErrCashAccountInvalid     = errors.New("cash account required")
	ErrCashImbalance          = errors.New("debit and credit must balance")
	ErrCashInsufficientBalance = errors.New("insufficient cash balance")
	ErrFundAlreadyClosed      = errors.New("petty cash fund already closed")
	ErrFundNotActive          = errors.New("petty cash fund not active")
	ErrInventoryCompleted     = errors.New("cash inventory already completed")
	ErrCurrencyMismatch       = errors.New("currency mismatch")
	ErrExchangeRateRequired   = errors.New("exchange rate required for foreign currency")
	ErrApprovalRequired       = errors.New("voucher must be approved before posting")
	ErrSelfCashApproval       = errors.New("cannot self-approve cash voucher")
)

// Advance errors
var (
	ErrAdvanceNotFound       = errors.New("advance request not found")
	ErrAdvanceAlreadyPaid    = errors.New("advance already paid")
	ErrAdvanceAlreadySettled = errors.New("advance already settled")
	ErrSettlementNotFound    = errors.New("advance settlement not found")
	ErrSettlementAlreadyPaid = errors.New("settlement already paid")
)

// Bank module errors
var (
	ErrBankStatementNotFound     = errors.New("bank statement not found")
	ErrStatementLineNotFound     = errors.New("bank statement line not found")
	ErrStatementAlreadyReconciled = errors.New("bank statement already reconciled")
	ErrStatementPeriodOverlap    = errors.New("statement period overlaps with existing")
	ErrReconciliationNotFound    = errors.New("bank reconciliation not found")
	ErrReconAlreadyCompleted     = errors.New("reconciliation already completed")
	ErrReconNotCompleted         = errors.New("reconciliation not completed")
	ErrReconDifferenceNotZero    = errors.New("reconciliation difference is not zero")
	ErrPaymentOrderNotFound      = errors.New("payment order not found")
	ErrPaymentOrderNotDraft      = errors.New("payment order is not in draft status")
	ErrCannotSelfApprovePayment  = errors.New("cannot self-approve payment order")
	ErrPaymentOrderAlreadyProcessed = errors.New("payment order already processed")
	ErrLoanAgreementNotFound     = errors.New("loan agreement not found")
	ErrLoanDisbursementOverLimit = errors.New("total disbursement exceeds principal amount")
	ErrLoanRepaymentNotFound     = errors.New("loan repayment not found")
	ErrTermDepositNotFound       = errors.New("term deposit not found")
	ErrDepositAlreadyMatured     = errors.New("deposit already matured")
	ErrPaymentBatchNotFound      = errors.New("payment batch not found")
	ErrBatchAlreadySubmitted     = errors.New("batch already submitted")

	ErrBeneficiaryNameRequired  = errors.New("beneficiary name is required")
	ErrBeneficiaryAccRequired   = errors.New("beneficiary account number is required")
	ErrBeneficiaryBankRequired  = errors.New("beneficiary bank is required")
	ErrFromBankAccRequired      = errors.New("source bank account is required")
	ErrPaymentDateRequired      = errors.New("payment date is required")
	ErrContractNoRequired       = errors.New("contract number is required")
	ErrLoanPrincipalRequired    = errors.New("loan principal amount is required")
	ErrInterestRateRequired     = errors.New("interest rate is required")
	ErrLoanDateRequired         = errors.New("loan start and maturity dates are required")
	ErrDepositAmountRequired    = errors.New("deposit amount is required")
	ErrDepositMinTerm           = errors.New("minimum term is 7 days")
	ErrDepositDateRequired      = errors.New("deposit start and maturity dates are required")
)

// Tax module errors
var (
	ErrDeclarationNotFound       = errors.New("tax declaration not found")
	ErrDeclarationTypeInvalid    = errors.New("invalid declaration type")
	ErrDeclarationStatusInvalid  = errors.New("invalid declaration status")
	ErrDeclarationAlreadySubmitted = errors.New("declaration already submitted")
	ErrDeclarationNotEditable    = errors.New("declaration is not editable")
	ErrCompanyIDRequired         = errors.New("company id is required")
	ErrPeriodNumberInvalid       = errors.New("invalid period number")
	ErrTaxRateNotFound           = errors.New("tax rate not found")
	ErrTaxRateCodeExists         = errors.New("tax rate code already exists")
	ErrTaxPaymentNotFound        = errors.New("tax payment not found")
	ErrPaymentAmountRequired     = errors.New("payment amount is required")
	ErrPaymentDueDateRequired    = errors.New("payment due date is required")
	ErrInvoiceNotFound           = errors.New("e-invoice not found")
	ErrInvoicePatternRequired    = errors.New("invoice pattern is required")
	ErrInvoiceNoLines            = errors.New("invoice must have at least one line")
	ErrInvoiceVATMismatch        = errors.New("VAT amount does not match line total * VAT rate")
	ErrInvoiceSubtotalMismatch   = errors.New("subtotal does not match sum of line totals")
	ErrInvoiceVATTotalMismatch   = errors.New("VAT amount does not match sum of line VAT")
	ErrInvoiceGrandTotalMismatch = errors.New("grand total must equal subtotal + VAT")
	ErrInvoiceStatusInvalid      = errors.New("invalid invoice status")
	ErrOriginalInvoiceRequired   = errors.New("original invoice ID required for adjustment/replacement/cancellation")
	ErrBuyerNameRequired         = errors.New("buyer name is required")
	ErrCalendarNotFound          = errors.New("tax calendar entry not found")
	ErrTaxAlertNotFound          = errors.New("tax alert not found")
	ErrAuditCaseNotFound         = errors.New("audit case not found")
	ErrValidationFailed          = errors.New("tax validation failed")
	ErrCalculationFailed         = errors.New("tax calculation failed")
	ErrXMLGenerationFailed       = errors.New("XML generation failed")

	// Opening balance errors
	ErrOpeningBalanceNotFound     = errors.New("opening balance not found")
	ErrOpeningBalanceExists       = errors.New("opening balance already exists for this account and period")
	ErrOpeningBalanceNotBalanced  = errors.New("total debit must equal total credit")
	ErrParentAccountBalance       = errors.New("parent account cannot have opening balance")
	ErrAmountRequired             = errors.New("debit or credit amount is required")
	ErrBothDebitAndCredit         = errors.New("cannot have both debit and credit, use one")
	ErrDuplicateOpeningBalance    = errors.New("duplicate opening balance for account in this period")
	ErrPeriodNotOpen              = errors.New("period is not open")
	ErrOpeningBalanceApproved     = errors.New("opening balance already approved, use correction")
	ErrOpeningBalanceRejected     = errors.New("opening balance was rejected")
	ErrOpeningBalanceImmutable    = errors.New("opening balance is immutable after approval")
	ErrSelfApprovalOB             = errors.New("cannot self-approve opening balance")
	ErrCorrectionReasonRequired   = errors.New("correction reason is required")
	ErrCarryForwardExists         = errors.New("carry-forward already exists for this period pair")
	ErrCarryForwardNotAllowed     = errors.New("cannot carry forward, target period has entries")
	ErrCircular99MappingNotFound  = errors.New("circular 99 mapping not found")
	ErrCircular99MappingExists    = errors.New("circular 99 mapping already exists")
	ErrMigrationIncomplete        = errors.New("migration is incomplete, some accounts not mapped")
	ErrEntityNotInCompany         = errors.New("entity does not belong to this company")
	ErrDetailSumMismatch          = errors.New("detail line sum must equal opening balance total")
	ErrOpeningBalanceAlreadySubmitted = errors.New("opening balance already submitted for approval")
	ErrPeriodNotClosed            = errors.New("source period must be closed for carry-forward")
)

// Purchase module errors
var (
	ErrSupplierNotFound       = errors.New("supplier not found")
	ErrSupplierCodeRequired   = errors.New("supplier code is required")
	ErrSupplierNameRequired   = errors.New("supplier name is required")
	ErrSupplierTaxCodeRequired = errors.New("supplier tax code is required")
	ErrSupplierCodeExists     = errors.New("supplier code already exists")
	ErrSupplierStatusInvalid  = errors.New("invalid supplier status")

	ErrPONumberRequired   = errors.New("PO number is required")
	ErrPOSupplierRequired = errors.New("supplier is required")
	ErrPODateRequired     = errors.New("order date is required")
	ErrPOStatusInvalid    = errors.New("invalid PO status")
	ErrPOLinesRequired    = errors.New("PO must have at least one line")
	ErrPONotFound         = errors.New("purchase order not found")
	ErrPOAlreadyApproved  = errors.New("PO already approved")
	ErrPOAlreadyCancelled = errors.New("PO already cancelled")
	ErrPOInvalidTransition = errors.New("invalid PO status transition")
	ErrPOCannotUpdate     = errors.New("PO cannot be updated in current status")

	ErrPOItemNameRequired     = errors.New("item name is required")
	ErrPOItemUnitRequired     = errors.New("unit is required")
	ErrPOItemQuantityRequired = errors.New("quantity must be positive")
	ErrPOItemPriceRequired    = errors.New("unit price must be non-negative")
	ErrPOItemAccountRequired  = errors.New("GL account is required")
	ErrPOItemVATAccountRequired = errors.New("VAT account is required")

	ErrGRNNumberRequired = errors.New("GRN number is required")
	ErrGRNPORequired     = errors.New("purchase order is required")
	ErrGRNDateRequired   = errors.New("receipt date is required")
	ErrGRNStatusInvalid  = errors.New("invalid GRN status")
	ErrGRNLinesRequired  = errors.New("GRN must have at least one line")
	ErrGRNNotFound       = errors.New("goods receipt note not found")
	ErrGRNAlreadyPosted  = errors.New("GRN already posted")
	ErrGRNInvalidTransition = errors.New("invalid GRN status transition")
	ErrGRNCannotUpdate   = errors.New("GRN cannot be updated in current status")

	ErrGRNItemNameRequired     = errors.New("item name is required")
	ErrGRNItemPOLineRequired   = errors.New("PO line reference is required")
	ErrGRNItemQtyRequired      = errors.New("quantity received must be non-negative")

	ErrInvoiceNumberRequired       = errors.New("invoice number is required")
	ErrInvoiceSupplierRequired     = errors.New("supplier is required")
	ErrInvoiceSupplierNameRequired = errors.New("supplier name is required")
	ErrInvoiceSupplierTaxCodeRequired = errors.New("supplier tax code is required")
	ErrInvoiceDateRequired         = errors.New("invoice date is required")
	ErrInvoiceStatusInvalidPurchase = errors.New("invalid invoice status")
	ErrInvoiceLinesRequired        = errors.New("invoice must have at least one line")
	ErrSupplierInvoiceNotFound     = errors.New("supplier invoice not found")
	ErrInvoiceAlreadyPosted        = errors.New("invoice already posted")
	ErrInvoiceInvalidTransition    = errors.New("invalid invoice status transition")
	ErrInvoiceCannotUpdate         = errors.New("invoice cannot be updated in current status")
	ErrInvoice3WayMismatch         = errors.New("3-way match failed: quantity or price mismatch")

	ErrInvoiceItemNameRequired     = errors.New("item name is required")
	ErrInvoiceItemQtyRequired      = errors.New("quantity must be positive")
	ErrInvoiceItemPriceRequired    = errors.New("unit price must be non-negative")
	ErrInvoiceItemAccountRequired  = errors.New("GL account is required")
	ErrInvoiceItemVATAccountRequired = errors.New("VAT account is required")

	ErrAPTransSupplierRequired = errors.New("supplier is required")
	ErrAPTransDateRequired     = errors.New("transaction date is required")
	ErrAPTransAmountRequired   = errors.New("amount must be non-zero")
	ErrAPTransTypeInvalid      = errors.New("invalid AP transaction type")
	ErrAPTransNotFound         = errors.New("AP transaction not found")

	ErrCostAllocInvoiceRequired = errors.New("invoice is required")
	ErrCostAllocAmountRequired  = errors.New("cost amount must be positive")
	ErrCostAllocTypeInvalid     = errors.New("invalid cost allocation type")
	ErrCostAllocMethodInvalid   = errors.New("invalid cost allocation method")

	// Requisition
	ErrRequisitionNumberRequired   = errors.New("requisition number is required")
	ErrRequisitionRequesterRequired = errors.New("requester is required")
	ErrRequisitionStatusInvalid    = errors.New("invalid requisition status")
	ErrRequisitionLinesRequired    = errors.New("requisition must have at least one line")
	ErrRequisitionNotFound         = errors.New("purchase requisition not found")
	ErrRequisitionInvalidTransition = errors.New("invalid requisition status transition")
	ErrRequisitionCannotUpdate     = errors.New("requisition cannot be updated in current status")
	ErrRequisitionItemNameRequired = errors.New("item name is required")
	ErrRequisitionItemQtyRequired  = errors.New("quantity must be positive")
	ErrRequisitionItemPriceRequired = errors.New("estimated price must be non-negative")
	ErrRequisitionItemAccountRequired = errors.New("GL account is required")
	ErrRequisitionNotApproved      = errors.New("requisition must be approved before conversion")

	// Purchase return / credit note (P2-2)
	ErrReturnGRNRequired        = errors.New("return GRN must reference an original GRN")
	ErrReturnGRNNotPosted       = errors.New("original GRN must be posted before return")
	ErrReturnGRNReturnAgain     = errors.New("cannot return a GRN that is itself a return")
	ErrReturnQtyExceeds         = errors.New("return quantity exceeds received balance")
	ErrCreditNoteTypeInvalid    = errors.New("credit note invoice_type must be credit_note")
	ErrCreditNoteOriginalRequired = errors.New("credit note must reference an original invoice")
	ErrCreditNoteOriginalNotPosted = errors.New("original invoice must be posted before credit note")
	ErrCreditNoteSupplierMismatch = errors.New("credit note supplier must match original invoice")
	ErrCreditNoteExceedsBalance = errors.New("credit note amount exceeds original invoice balance")

	// FX revaluation (P2-4)
	ErrFXRevaluationDateRequired  = errors.New("revaluation date is required")
	ErrFXRevaluationStatusInvalid = errors.New("invalid FX revaluation status")
	ErrFXRevaluationLinesRequired = errors.New("FX revaluation must have at least one line")
	ErrFXRevaluationNotFound      = errors.New("FX revaluation not found")
	ErrFXRevaluationRateMissing   = errors.New("exchange rate not found for currency on revaluation date")
	ErrFXRevaluationEmpty         = errors.New("no open foreign-currency invoices to revalue")
	ErrFXRevaluationAlreadyPosted = errors.New("FX revaluation already posted")

	ErrProvisionDateRequired   = errors.New("provision as-of date is required")
	ErrProvisionNoLines        = errors.New("provision has no lines")
	ErrProvisionNotFound       = errors.New("doubtful debt provision not found")
	ErrProvisionNoPrepayments  = errors.New("no outstanding supplier prepayments to provision")

	// Sale module errors
	ErrCustomerNotFound       = errors.New("customer not found")
	ErrCustomerCodeRequired   = errors.New("customer code is required")
	ErrCustomerNameRequired   = errors.New("customer name is required")
	ErrCustomerTaxCodeRequired = errors.New("customer tax code is required")
	ErrCustomerCodeExists     = errors.New("customer code already exists")
	ErrCustomerStatusInvalid  = errors.New("invalid customer status")

	ErrSONumberRequired   = errors.New("SO number is required")
	ErrSONumberExists     = errors.New("SO number already exists")
	ErrSOCustomerRequired = errors.New("customer is required")
	ErrSODateRequired     = errors.New("order date is required")
	ErrSOStatusInvalid    = errors.New("invalid SO status")
	ErrSOLinesRequired    = errors.New("SO must have at least one line")
	ErrSONotFound         = errors.New("sales order not found")
	ErrSOAlreadyApproved  = errors.New("SO already approved")
	ErrSOAlreadyCancelled = errors.New("SO already cancelled")
	ErrSOInvalidTransition = errors.New("invalid SO status transition")
	ErrSOCannotUpdate     = errors.New("SO cannot be updated in current status")

	ErrSOItemNameRequired     = errors.New("item name is required")
	ErrSOItemUnitRequired     = errors.New("unit is required")
	ErrSOItemQtyRequired      = errors.New("quantity must be positive")
	ErrSOItemPriceRequired    = errors.New("unit price must be non-negative")
	ErrSOItemAccountRequired  = errors.New("GL account is required")
	ErrSOItemVATAccountRequired = errors.New("VAT account is required")

	ErrDNNumberRequired   = errors.New("delivery note number is required")
	ErrDNNumberExists     = errors.New("delivery note number already exists")
	ErrDNSORequired       = errors.New("sales order is required")
	ErrDNDateRequired     = errors.New("delivery date is required")
	ErrDNStatusInvalid    = errors.New("invalid delivery note status")
	ErrDNLinesRequired    = errors.New("delivery note must have at least one line")
	ErrDNNotFound         = errors.New("delivery note not found")
	ErrDNAlreadyPosted    = errors.New("delivery note already posted")
	ErrDNInvalidTransition = errors.New("invalid delivery note status transition")
	ErrDNCannotUpdate     = errors.New("delivery note cannot be updated in current status")

	ErrDNItemNameRequired   = errors.New("item name is required")
	ErrDNItemSOLineRequired = errors.New("SO line reference is required")
	ErrDNItemQtyRequired    = errors.New("quantity delivered must be positive")

	ErrInvNumberRequired       = errors.New("invoice number is required")
	ErrInvNumberExists         = errors.New("invoice number already exists")
	ErrInvCustomerRequired     = errors.New("customer is required")
	ErrInvCustomerNameRequired = errors.New("customer name is required")
	ErrInvCustomerTaxCodeRequired = errors.New("customer tax code is required")
	ErrInvDateRequired         = errors.New("invoice date is required")
	ErrInvStatusInvalid        = errors.New("invalid invoice status")
	ErrInvLinesRequired        = errors.New("invoice must have at least one line")
	ErrInvNotFound             = errors.New("customer invoice not found")
	ErrInvAlreadyPosted        = errors.New("invoice already posted")
	ErrInvInvalidTransition    = errors.New("invalid invoice status transition")
	ErrInvCannotUpdate         = errors.New("invoice cannot be updated in current status")
	ErrInv2WayMismatch         = errors.New("2-way match failed: quantity or price mismatch")
	ErrInvAlreadySigned        = errors.New("invoice already signed")
	ErrInvNotSigned            = errors.New("invoice not yet signed")
	ErrInvAlreadySubmitted     = errors.New("invoice already submitted to GDT")

	ErrInvItemNameRequired    = errors.New("item name is required")
	ErrInvItemQtyRequired     = errors.New("quantity must be positive")
	ErrInvItemPriceRequired   = errors.New("unit price must be non-negative")
	ErrInvItemAccountRequired = errors.New("GL account is required")
	ErrInvItemVATAccountRequired = errors.New("VAT account is required")

	ErrRcpNumberRequired   = errors.New("receipt number is required")
	ErrRcpNumberExists     = errors.New("receipt number already exists")
	ErrRcpCustomerRequired = errors.New("customer is required")
	ErrRcpDateRequired     = errors.New("receipt date is required")
	ErrRcpAmountRequired   = errors.New("amount must be positive")
	ErrRcpStatusInvalid    = errors.New("invalid receipt status")
	ErrRcpNotFound         = errors.New("customer receipt not found")
	ErrRcpAlreadyPosted    = errors.New("receipt already posted")
	ErrRcpInvalidTransition = errors.New("invalid receipt status transition")
	ErrRcpAllocExceedsBalance = errors.New("allocation exceeds invoice balance")
	ErrRcpAllocExceedsReceipt = errors.New("allocation exceeds receipt unallocated amount")

	ErrCNNumberRequired      = errors.New("credit note number is required")
	ErrCNNumberExists        = errors.New("credit note number already exists")
	ErrCNOriginalInvRequired = errors.New("original invoice is required")
	ErrCNCustomerRequired    = errors.New("customer is required")
	ErrCNDateRequired        = errors.New("return date is required")
	ErrCNStatusInvalid       = errors.New("invalid credit note status")
	ErrCNLinesRequired       = errors.New("credit note must have at least one line")
	ErrCNNotFound            = errors.New("credit note not found")
	ErrCNAlreadyPosted       = errors.New("credit note already posted")

	ErrSQNumberRequired      = errors.New("quotation number is required")
	ErrSQNumberExists        = errors.New("quotation number already exists")
	ErrSQNotFound            = errors.New("quotation not found")

	ErrARTransCustomerRequired = errors.New("customer is required")
	ErrARTransDateRequired     = errors.New("transaction date is required")
	ErrARTransAmountRequired   = errors.New("amount must be non-zero")
	ErrARTransTypeInvalid      = errors.New("invalid AR transaction type")
	ErrARTransNotFound         = errors.New("AR transaction not found")
	ErrCreditLimitExceeded     = errors.New("credit limit exceeded")

	// Warehouse module errors
	ErrWarehouseCodeRequired  = errors.New("warehouse code is required")
	ErrWarehouseNameRequired  = errors.New("warehouse name is required")
	ErrWarehouseNotFound      = errors.New("warehouse not found")
	ErrWarehouseCodeExists    = errors.New("warehouse code already exists")

	ErrCategoryCodeRequired   = errors.New("category code is required")
	ErrCategoryNameRequired   = errors.New("category name is required")
	ErrCategoryNotFound       = errors.New("item category not found")
	ErrCategoryCodeExists     = errors.New("category code already exists")

	ErrItemCodeRequired       = errors.New("item code is required")
	ErrItemNameRequired       = errors.New("item name is required")
	ErrItemUnitRequired       = errors.New("unit is required")
	ErrItemNotFound           = errors.New("item not found")
	ErrItemCodeExists         = errors.New("item code already exists")
	ErrValuationMethodInvalid = errors.New("invalid valuation method")

	ErrBalanceNotFound        = errors.New("stock balance not found")
	ErrBalanceExists          = errors.New("stock balance already exists for period")

	ErrTransNotFound          = errors.New("inventory transaction not found")

	ErrTransferNumberRequired = errors.New("transfer number is required")
	ErrTransferFromWHRequired = errors.New("from warehouse is required")
	ErrTransferToWHRequired   = errors.New("to warehouse is required")
	ErrTransferSameWH         = errors.New("from and to warehouse must be different")
	ErrTransferItemsRequired  = errors.New("transfer must have at least one item")
	ErrTransferNotFound       = errors.New("stock transfer not found")
	ErrTransferInvalidStatus  = errors.New("invalid transfer status transition")

	ErrAdjNumberRequired      = errors.New("adjustment number is required")
	ErrAdjWarehouseRequired   = errors.New("warehouse is required for adjustment")
	ErrAdjItemsRequired       = errors.New("adjustment must have at least one item")
	ErrAdjTypeRequired        = errors.New("adjustment type is required")
	ErrAdjTypeInvalid         = errors.New("invalid adjustment type")
	ErrAdjNotFound            = errors.New("stock adjustment not found")
	ErrAdjInvalidStatus       = errors.New("invalid adjustment status transition")

	ErrTakeNumberRequired     = errors.New("take number is required")
	ErrTakeWarehouseRequired  = errors.New("warehouse is required for stock take")
	ErrTakeDateRequired       = errors.New("take date is required")
	ErrTakeItemsRequired      = errors.New("stock take must have at least one item")
	ErrTakeNotFound           = errors.New("stock take not found")
	ErrTakeInvalidStatus      = errors.New("invalid stock take status transition")

	ErrValRunDateRequired     = errors.New("valuation date is required")
	ErrValRunNotFound         = errors.New("valuation run not found")
)

// Fixed Asset module errors
var (
	ErrFANotFound                   = errors.New("fixed asset not found")
	ErrFACodeExists                 = errors.New("fixed asset code already exists")
	ErrFACodeRequired               = errors.New("fixed asset code is required")
	ErrFANameRequired               = errors.New("fixed asset name is required")
	ErrFACategoryRequired           = errors.New("fixed asset category is required")
	ErrFACategoryNotFound           = errors.New("fixed asset category not found")
	ErrFACategoryCodeExists         = errors.New("fixed asset category code already exists")
	ErrFAOriginalCostInvalid        = errors.New("original cost must be non-negative")
	ErrFAUsefulLifeInvalid          = errors.New("useful life must be positive")
	ErrFADepreciationMethodInvalid  = errors.New("invalid depreciation method")
	ErrFAStatusInvalid              = errors.New("invalid fixed asset status")
	ErrFAAssetAccountRequired       = errors.New("asset account is required")
	ErrFADepreciationAccountRequired = errors.New("depreciation account is required")
	ErrFAExpenseAccountRequired     = errors.New("expense account is required")
	ErrFACategoryCodeRequired       = errors.New("category code is required")
	ErrFACategoryNameRequired       = errors.New("category name is required")
	ErrFACategoryLevelInvalid       = errors.New("category level must be 1-3")
	ErrFACategorySelfParent         = errors.New("category cannot be its own parent")
	ErrFANotActive                  = errors.New("fixed asset is not active")
	ErrFANotDepreciating            = errors.New("fixed asset is not depreciating")
	ErrFADisposalIncomplete         = errors.New("disposal details incomplete")
	ErrFADepreciationExists         = errors.New("depreciation already exists for this period")
	ErrFAPeriodNotProcessed         = errors.New("previous period depreciation not processed")
	ErrFADepartmentChangeNotAllowed = errors.New("department change not allowed during depreciation")
	ErrFARevaluationRequiresFairValue = errors.New("fair value is required for revaluation")
	ErrFAImpairmentAmountInvalid    = errors.New("impairment amount must be positive")
	ErrFAAllocationPctInvalid       = errors.New("allocation percentages must sum to 100")
	ErrFAAllocationPctSum           = errors.New("allocation percentages must sum to 100")
	ErrFATransferSameDepartment     = errors.New("asset already assigned to this department")
	ErrFAAcquisitionDateRequired    = errors.New("acquisition date is required")
	ErrFADepartmentRequired         = errors.New("department is required")
	ErrFASourceInvalid              = errors.New("invalid fixed asset source")
	ErrFACIPTransferNotApplicable   = errors.New("asset is not a CIP, cannot transfer")
	ErrFASuspensionNotApplicable    = errors.New("asset is not depreciating, cannot suspend")
	ErrFAResumeNotApplicable        = errors.New("asset is not suspended, cannot resume")
)
